config/routes.rb
Rails.application.routes.draw do
  resources :orders
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  BUY_TRANSACTION_TYPE = 'BUY'
  SELL_TRANSACTION_TYPE = 'SELL'

  belongs_to :user
  validates :user, presence: true
  validates :transaction_type, inclusion: { in: [Order::BUY_TRANSACTION_TYPE, Order::SELL_TRANSACTION_TYPE ], message: "%{value} is not a valid transaction type" }, presence: true
  validates :price_per_kg, numericality: {  greater_than_or_equal_to: 0 }, presence:true
  validates :quantity,numericality: {  greater_than: 0 }, presence:true



  def self.summary_prices_per_pricepoint(transaction_type, order)
    Order.where(transaction_type: transaction_type)
         .group(:price_per_kg).order(price_per_kg: order)
         .pluck('sum(quantity) as total_quantity','price_per_kg')
         .map { |total_quantity, price_per_kg| {quantity: total_quantity, price_per_kg: price_per_kg} }

  end

  def self.summary_prices_per_price_point_for_sale
    summary_prices_per_pricepoint(Order::SELL_TRANSACTION_TYPE,:asc)
  end

  def self.summary_prices_per_price_point_for_buy
    summary_prices_per_pricepoint(Order::BUY_TRANSACTION_TYPE,:desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!, unless: :devise_controller?	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    @order.user = current_user

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.fetch(:order).permit(:quantity,:price_per_kg,:transaction_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/home/index.html.erb
<h1> Home page </h1>
<%= link_to 'View Orders', orders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Propoly test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <p><%= current_user.email %> <%= button_to "Sign out", destroy_user_session_path, :method => :delete %></p>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :price_per_kg %>
    <%= form.number_field :price_per_kg, step: 0.01, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, step: 0.01, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :transaction_type %>
    <%= form.select :transaction_type, [Order::BUY_TRANSACTION_TYPE, Order::SELL_TRANSACTION_TYPE], {}, class: 'form-control' %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Live Orders</h1>

<table id="orders">
  <thead>
    <th>User</th>
    <th>Quantity (kg)</th>
    <th>Price (£ per kg)</th>
    <th>Transaction</th>
    <th></th>
    <th></th>
  </thead>
  <tbody>

  <% @orders.each do |order| %>
    <tr>
      <td><%= order.user.email %></td>
      <td><%= order.quantity %></td>
      <td><%= order.price_per_kg %></td>
      <td><%= order.transaction_type %></td>
      <td><%= button_to 'Edit', edit_order_path(order), method: :get %></td>
      <td><%= button_to 'Delete', order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "New order", new_order_path %>


<h1>Sell summary</h1>
<table id="order_sell_summary">
    <thead>
      <th>Quantity</th>
      <th>Price (£ per kg)</th>
    </thead>
    <tbody>
      <% Order.summary_prices_per_price_point_for_sale.each do | summary_line | %>
      <tr>
        <td><%= summary_line[:quantity] %></td>
        <td><%= summary_line[:price_per_kg] %></td>
      </tr>
      <% end %>
    </tbody>
</table>

<h1>Buy summary</h1>
<table id="order_buy_summary">
    <thead>
      <th>Quantity</th>
      <th>Price (£ per kg)</th>
    </thead>
    <tbody>
      <% Order.summary_prices_per_price_point_for_buy.each do | summary_line | %>
      <tr>
        <td><%= summary_line[:quantity] %></td>
        <td><%= summary_line[:price_per_kg] %></td>
      </tr>
      <% end %>
    </tbody>
</table>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>